server:
  port: 7900
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/day8?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: "000000"
      driver-class-name: com.mysql.cj.jdbc.Driver
      min-idle: 5
      max-active: 100
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 50
      remove-abandoned: true
      filters: stat