
server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-gateway-zuul
zuul:
  routes:
    users:  #  唯一就行
      path: /user-url/**
      service-id: microservice-provider-user
ribbon:
  eureka:
    enable: false
microservice-provider-user:   #  这里是ribbon要请求的微服务的serviceId
  ribbon:
    listOfServers: http://localhsot:7900,http://localhost:7901