#j简单的使用feign
server:
  port: 7901
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
logging:
  level:
    com.itmuch.cloud.microservicesimpleconsumermovie.feign.UserFeignClient: debug