
server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix-propagation
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000   # 设置hystrix的响应超出时间，默认是1秒