
server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie -ribbon -without-eureka
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
# 配置ribbon不使用eureka
ribbon:
  eureka:
    enabled: false

microservice-provider-user:
  ribbon:
    listOfServers: localhost:7900
