
server:
  port: 8761
eureka:
  datacenter: cloud    # 配置eureka主界面上的System status of datacenter
  environment: product   # 配置eureka 主界面上的System status of enviroment
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false
#  dashboard:
#    enabled: true   #  配置eureka主界面是否访问。默认是true
#    path: /x    #  配置eureka主界面访问的路径
#    healthcheck:
#      enabled: true  #配置健康检查
security:
  basic:
    enabled: true
  user:
    name: user
    password: password
